export const images = {
  registerScreen: require('./background.images/registerScreenBg.png'),
  AppLogo: require('./logo.images/Applogo.png'),
  AppLogoicon: require('./logo.images/AppLogoicon.png'),
  googleIcon: require('./icons.images/googleicon.png'),
  avatar: require('./icons.images/avatar.png'),
  contactSupport: require('./icons.images/contactSupport.png'),
  arrow: require('./icons.images/arrow.png'),
  delete: require('./icons.images/delete.png'),
  lock: require('./icons.images/lock.png'),
  tc: require('./icons.images/T&C.png'),
  backArrow: require('./icons.images/backArrow.png'),
  searchIcon: require('./icons.images/searchIcon.png'),
  heartIcon: require('./icons.images/heartIcon.png'),
  filterIcon: require('./icons.images/filter.png'),
};
